### ISSUE TITLE
How to sort the todo list?

### ISSUE THREAD

**Issue by michaellenahan** [NiloCK/tuido#10]
Firstly, thank you for this project, it's really helpful to me. I keep my notes in *.md files and when to-do items arise I add them in xit notation. Having all my to-do's in one place makes a huge difference for me!

My question: is there a way to sort the list alphabetically?

Here is roughly how my "todo" tab looks at the moment:

> [ ] PROJ-2878 Adding a review for the item gives an error
  [@] #! menu code needs refactoring
  [@] #! PROJ-2890 problem with playlist
  [@] #! PROJ-2832 Remove unneeded directory
  [ ] #! PROJ-2746 completely remove the xxx integration code
  [ ] #!!!! In January I need do something super important
  [ ] ask my manager for certain equipment
  [ ] Check software version of certain dependency

It would be great if I could sort it, is there a way to do that? Thanks!

**Comment by NiloCK** [comment]
Hi @michaellenahan. Happy to hear you enjoy the project.

The sorting works like this:
- sort by how `important` items are (the number of leading `!`s)
- sort by the specified due dates, if any due date is present (eg, with the `#due=` tag)
- otherwise, do not alter the order of items

In the non-altering case, items here would be grouped by their file-of-origin, and listed in the order in which they occurred in the file.

In response to your issue, I just pushed a new release that sorts by
- importance
- due-date (if present)
- alphabetical

I'm not sure if I like that for my own purposes, so a future release may include something like a `sortStyle` config option.

**Comment by michaellenahan** [comment]
Thank you so much for this: https://github.com/NiloCK/tuido/commit/7b380ae66fbd53718c7fb85b459bcfeb4e772414

In my case, using !!! will be enough, I didn't quite understand how that worked, and was trying a somewhat clumsy home-made solution with hash-tags. Now that I understand how `Importance` works with the exclamation-marks, that's enough for me.

So if it's not needed by you, maybe in the spirit of keeping the project free of unnecessary complication, you may choose to revert it, or keep it if you think it's useful generally. Thanks again, I love this project!

**Comment by michaellenahan** [comment]
I created a merge request to update the README, should you decide to revert the commit, then the last bullet point can be changed to reflect that.
https://github.com/NiloCK/tuido/pull/11/files

**Comment by NiloCK** [comment]
> In my case, using !!! will be enough, I didn't quite understand how that worked, and was trying a somewhat clumsy home-made solution with hash-tags. Now that I understand how `Importance` works with the exclamation-marks, that's enough for me.

Great. Note also that when you're in tuido you can bump / decrement the importance of the current item with `!` and `1` - a pretty quick way to maintain what's on top and "above the fold".

I think I'll leave the alphabetical sorting in for a bit and see how it feels.
